displayName: Cookie value extractor with regex
type: middleware

import: github.com/bonovoxly/extract-cookie-regex

summary: |
  Takes specified cookie value (from Cookie header)
  and put it in a header you want. You can declare prefix for value,
  which will be added to cookie value.
  If there is no such cookie, the header value will not be set.
  Can use Regex to find correct cookie names (for Cognito, for instance).

testData:
  cookieName: test_cookie_with_auth_token
  headerNameForCookieValue: Authorization
  cookieValuePrefix: 'Bearer '
